backend:
  name: git-gateway
  branch: main # Check if your GitHub branch is 'main' or 'master'

media_folder: "public/images/products" # Where images will be saved
public_folder: "/images/products" # Where the website will look for images

collections:
  - name: "products"
    label: "Products"
    folder: "content/products" # CHANGE THIS to where your product files live
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Product Image", name: "image", widget: "image" }
